//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forge.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forge.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string BodyZone_Core {
            get {
                return ResourceManager.GetString("BodyZone_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Body.
        /// </summary>
        internal static string BodyZone_FullBody {
            get {
                return ResourceManager.GetString("BodyZone_FullBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Body.
        /// </summary>
        internal static string BodyZone_Lower {
            get {
                return ResourceManager.GetString("BodyZone_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Body.
        /// </summary>
        internal static string BodyZone_Upper {
            get {
                return ResourceManager.GetString("BodyZone_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Library.
        /// </summary>
        internal static string ExerciseLibrary_Title {
            get {
                return ResourceManager.GetString("ExerciseLibrary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ExerciseLibraryPage_Category {
            get {
                return ResourceManager.GetString("ExerciseLibraryPage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises match your filters.
        /// </summary>
        internal static string ExerciseLibraryPage_NoMatch {
            get {
                return ResourceManager.GetString("ExerciseLibraryPage_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Exercises.
        /// </summary>
        internal static string ExerciseLibraryPage_Search {
            get {
                return ResourceManager.GetString("ExerciseLibraryPage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ExerciseLibraryPage_SearchBtn {
            get {
                return ResourceManager.GetString("ExerciseLibraryPage_SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Zone.
        /// </summary>
        internal static string ExerciseLibraryPage_Zone {
            get {
                return ResourceManager.GetString("ExerciseLibraryPage_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap gear you own too toggle!.
        /// </summary>
        internal static string GearPage_TapToToggleCTA {
            get {
                return ResourceManager.GetString("GearPage_TapToToggleCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string GearPage_Title {
            get {
                return ResourceManager.GetString("GearPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITNESS FORGE.
        /// </summary>
        internal static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Training.
        /// </summary>
        internal static string Home_MainCTA_Btn {
            get {
                return ResourceManager.GetString("Home_MainCTA_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Stats.
        /// </summary>
        internal static string Home_StatCard_Title {
            get {
                return ResourceManager.GetString("Home_StatCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith Thy Sinew.
        /// </summary>
        internal static string Home_Tagline {
            get {
                return ResourceManager.GetString("Home_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Quest.
        /// </summary>
        internal static string QuestCard_CompleteBTN {
            get {
                return ResourceManager.GetString("QuestCard_CompleteBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string QuestCard_UndoComplete {
            get {
                return ResourceManager.GetString("QuestCard_UndoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log any cardio: rides, runs, brisk walks, circuits..
        /// </summary>
        internal static string QuestPage_ConditioningQuest_Hint {
            get {
                return ResourceManager.GetString("QuestPage_ConditioningQuest_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioning.
        /// </summary>
        internal static string QuestPage_ConditioningQuest_Title {
            get {
                return ResourceManager.GetString("QuestPage_ConditioningQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Focus.
        /// </summary>
        internal static string QuestPage_DailyFocus {
            get {
                return ResourceManager.GetString("QuestPage_DailyFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quests yet...
        /// </summary>
        internal static string QuestPage_EmptyQuests {
            get {
                return ResourceManager.GetString("QuestPage_EmptyQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        internal static string QuestPage_MobilityQuest_Title {
            get {
                return ResourceManager.GetString("QuestPage_MobilityQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Day.
        /// </summary>
        internal static string QuestPage_RecoveryBadge {
            get {
                return ResourceManager.GetString("QuestPage_RecoveryBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery ({0}).
        /// </summary>
        internal static string QuestPage_RecoveryHeader_Format {
            get {
                return ResourceManager.GetString("QuestPage_RecoveryHeader_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string QuestPage_StrengthQuest_Title {
            get {
                return ResourceManager.GetString("QuestPage_StrengthQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Quests.
        /// </summary>
        internal static string QuestPage_SubHeader_Daily {
            get {
                return ResourceManager.GetString("QuestPage_SubHeader_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long is the road to Mordor....
        /// </summary>
        internal static string QuestPage_Subheader_SubHint {
            get {
                return ResourceManager.GetString("QuestPage_Subheader_SubHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Quests.
        /// </summary>
        internal static string QuestPage_SubHeader_Weekly {
            get {
                return ResourceManager.GetString("QuestPage_SubHeader_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string QuestPage_Title {
            get {
                return ResourceManager.GetString("QuestPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} XP earned.
        /// </summary>
        internal static string QuestPage_XpDialog_Message_Format {
            get {
                return ResourceManager.GetString("QuestPage_XpDialog_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice!.
        /// </summary>
        internal static string QuestPage_XpDialog_Title {
            get {
                return ResourceManager.GetString("QuestPage_XpDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioning Quest.
        /// </summary>
        internal static string QuestService_CategoryConditioning {
            get {
                return ResourceManager.GetString("QuestService_CategoryConditioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string QuestService_CategoryDefault {
            get {
                return ResourceManager.GetString("QuestService_CategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility Quest.
        /// </summary>
        internal static string QuestService_CategoryMobility {
            get {
                return ResourceManager.GetString("QuestService_CategoryMobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength Quest.
        /// </summary>
        internal static string QuestService_CategoryStrength {
            get {
                return ResourceManager.GetString("QuestService_CategoryStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVL.
        /// </summary>
        internal static string StatCard_lvl {
            get {
                return ResourceManager.GetString("StatCard_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string StatCard_XPLabel {
            get {
                return ResourceManager.GetString("StatCard_XPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Stats.
        /// </summary>
        internal static string StatsPage_StatsCard {
            get {
                return ResourceManager.GetString("StatsPage_StatsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string StatsPage_Title {
            get {
                return ResourceManager.GetString("StatsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        internal static string TabNavigation_CheckIn {
            get {
                return ResourceManager.GetString("TabNavigation_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild.
        /// </summary>
        internal static string TabNavigation_Guild {
            get {
                return ResourceManager.GetString("TabNavigation_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabNavigation_Home {
            get {
                return ResourceManager.GetString("TabNavigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string TabNavigation_Quests {
            get {
                return ResourceManager.GetString("TabNavigation_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabNavigation_Settings {
            get {
                return ResourceManager.GetString("TabNavigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string TabNavigation_Stats {
            get {
                return ResourceManager.GetString("TabNavigation_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        internal static string TabNavigation_Train {
            get {
                return ResourceManager.GetString("TabNavigation_Train", resourceCulture);
            }
        }
    }
}
