//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forge.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forge.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITNESS FORGE.
        /// </summary>
        internal static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Training.
        /// </summary>
        internal static string Home_MainCTA_Btn {
            get {
                return ResourceManager.GetString("Home_MainCTA_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Stats.
        /// </summary>
        internal static string Home_StatCard_Title {
            get {
                return ResourceManager.GetString("Home_StatCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith Thy Sinew.
        /// </summary>
        internal static string Home_Tagline {
            get {
                return ResourceManager.GetString("Home_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVL.
        /// </summary>
        internal static string StatCard_lvl {
            get {
                return ResourceManager.GetString("StatCard_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string StatCard_XPLabel {
            get {
                return ResourceManager.GetString("StatCard_XPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        internal static string TabNavigation_CheckIn {
            get {
                return ResourceManager.GetString("TabNavigation_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild.
        /// </summary>
        internal static string TabNavigation_Guild {
            get {
                return ResourceManager.GetString("TabNavigation_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabNavigation_Home {
            get {
                return ResourceManager.GetString("TabNavigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string TabNavigation_Quests {
            get {
                return ResourceManager.GetString("TabNavigation_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabNavigation_Settings {
            get {
                return ResourceManager.GetString("TabNavigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string TabNavigation_Stats {
            get {
                return ResourceManager.GetString("TabNavigation_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        internal static string TabNavigation_Train {
            get {
                return ResourceManager.GetString("TabNavigation_Train", resourceCulture);
            }
        }
    }
}
